name 'iis-demo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures iis-demo'
long_description 'Installs/Configures iis-demo'
version '0.2.1'
